function eegplugin_batch_context(fig,try_strings,catch_strings)

%--------------------------------------------------------------------------
% Get File menu handle...
%--------------------------------------------------------------------------
filemenu=findobj(fig,'Label','File');


%% context menu
uimenu(filemenu,'Label','Context configuration', ...
                'separator','on', ...
                'callback','CONTEXT_CONFIG=pop_context_edit;');

%% batch menu
batchmenu  = uimenu( filemenu, 'Label', 'Batch','separator','on');

% create menu commands
% run history template batch...
cmd='LASTCOM = pop_runhtb();';
finalcmdRHT=[try_strings.no_check cmd catch_strings.store_and_hist];

% save history template batch file...
cmd='LASTCOM = pop_savehtb(EEG);';
finalcmdSHT=[try_strings.no_check cmd catch_strings.store_and_hist];

% batch configuration ... this should all be redured to and edit gui (like
% context and vised)

% New
%cmdNBC=['clear global BATCH_CONFIG;',...
%     'global BATCH_CONFIG;', ...
%     'BATCH_CONFIG=batchconfig_obj;', ...
%     'properties=batchconfig2propgrid();' ...
%     'properties = properties.GetHierarchy();' ...
%     'bcp=PropertyGrid(''Properties'', properties);'...
%     'uiwait;' ...
%     'BATCH_CONFIG=propgrid2batchconfig(bcp);'];

% Load
%cmdLBC=['pop_loadbatchconfig();', ...
%     'global BATCH_CONFIG;', ...
%     'properties=batchconfig2propgrid();' ...
%     'properties = properties.GetHierarchy();' ...
%     'bcp=PropertyGrid(''Properties'', properties);'...
%     'uiwait;' ...
%     'BATCH_CONFIG=propgrid2batchconfig(bcp);'];

% Edit
%cmdEBC=['properties=batchconfig2propgrid();' ...
%     'properties = properties.GetHierarchy();' ...
%     'bcp=PropertyGrid(''Properties'', properties);' ...
%     'uiwait;' ...
%     'BATCH_CONFIG=propgrid2batchconfig(bcp);'];

% Save
%cmdSBC='pop_savebatchconfig();';

% Clear
%cmdCBC='clear global BATCH_CONFIG';

% Add submenus to the "Batch" submenu.
%-------------------------------------
uimenu(batchmenu,'label','Save History Template Batching file (*.htb)','callback',finalcmdSHT);
uimenu(batchmenu,'label','Run history template batch','callback',finalcmdRHT);
%configmenu=uimenu(batchmenu,'label','batch configuration file');

uimenu(batchmenu,'Label','Batch configuration', ...
                'callback','BATCH_CONFIG=pop_batch_edit;');
%uimenu(configmenu,'label','New','callback',cmdNBC);
%uimenu(configmenu,'label','Load','callback',cmdLBC);
%uimenu(configmenu,'label','Edit properties','callback',cmdEBC);
%uimenu(configmenu,'label','Save','callback',cmdSBC);
%uimenu(configmenu,'label','Clear','callback',cmdCBC);


