function BATCH_CONFIG = pop_batch_edit

com = ''; % this initialization ensure that the function will return something
% if the user press the cancel button

global BATCH_CONFIG
if isempty(BATCH_CONFIG);
    BATCH_CONFIG=batchconfig_obj;
end

%PropGridStr=['global bcp;' ...
%    'properties=batchconfig2propgrid();' ...
%    'properties = properties.GetHierarchy();' ...
%    'bcp = PropertyGrid(gcf,' ...
%    '''Properties'', properties,' ...
%    '''Position'', [.36 .1 .6 .84]);' ...
%    ];

% pop up window
% -------------
if nargin < 4
    
    results=inputgui( ...
        'geom', ...
        {...
        {6 20 [0 0] [1 1]} ... %1 this is just to control the size of the GUI
        {6 20 [0.05 0] [2 1]} ... %2
        {6 20 [0.05 1] [2 1]} ... %2
        {6 20 [0.05 2] [2 12]} ... %2
        ...{6 20 [4.8 0] [1.13 1]} ... %3
        {6 20 [0.05 14] [2 1]} ... %4
        {6 20 [0.05 15] [2 1]} ... %5
        {6 20 [0.05 16] [2 1]} ... %5
...        {6 20 [0.05 18] [1 1]} ... %6
...        {6 20 [.9 18] [5 1]} ... %6
...        {6 20 [0.05 19] [1 1]} ... %2.5
...        {6 20 [.9 19] [5 1]} ... %6
        }, ...
        'uilist', ...
        {...
        {'Style', 'text', 'tag','txt_bcfp','string',blanks(20)} ... %1 this is just to control the size of the GUI
        {'Style', 'pushbutton', 'string', 'get Batch config file names', ...
        'callback', ...
        ['[bcfgFName, bcfgFPath] = uigetfile(''*.cfg'',''Select batch configuration file:'',''*.cfg'',''multiselect'',''on'');', ...
        'if isnumeric(bcfgFName);return;end;', ...
        'set(findobj(gcbf,''tag'',''edt_bcp''),''string'',bcfgFPath);', ...
        'set(findobj(gcbf,''tag'',''edt_bcn''),''string'',bcfgFName);']} ... %2
        {'Style', 'edit', 'tag','edt_bcp'} ... %4
        {'Style', 'edit', 'max', 500, 'tag', 'edt_bcn'}, ... %6
...        {'Style', 'pushbutton', 'string', 'get dir to clipboard', ...
...        'callback', ...
...        'dirname=uigetdir;clipboard(''copy'',dirname);'} ... %25
        {'Style', 'pushbutton','string','Clear/Load', ...
        'callback', ...
        ['fname=get(findobj(gcbf,''tag'',''edt_bcn''),''string'');',...
         'if ~iscell(fname);fname={fname};end;', ...
         'fpath=get(findobj(gcbf,''tag'',''edt_bcp''),''string'');',...
         'clear global BATCH_CONFIG;global BATCH_CONFIG;', ...
         'for i=1:length(fname);', ...
         '    if isempty(BATCH_CONFIG);', ...
         '        evalin(''base'',[''global BATCH_CONFIG;load('''''',fullfile(fpath,fname{i}),'''''',''''-mat'''');'']);', ...
         '        if ~strcmp(BATCH_CONFIG.file_name,fname{i});', ...
         '            disp(''changing file_name property...'');', ...
         '            BATCH_CONFIG.file_name=fname{i};', ...
         '        end;', ....
         '    else;', ...
         '        tmp=load(fullfile(fpath,fname{i}),''-mat'');', ...
         '        if ~strcmp(tmp.BATCH_CONFIG.file_name,fname{i});', ...
         '            disp(''changing file_name property...'');', ...
         '            tmp.BATCH_CONFIG.file_name=fname{i};', ...
         '        end;', ...
         '        BATCH_CONFIG=[BATCH_CONFIG,tmp.BATCH_CONFIG];', ...
         '    end;', ...
         'end;', ...
         ...'fnames=get(findobj(gcbf,''tag'',''edt_bcn''),''string'');', ...
         ...'disp(fnames);',...
         'global bcp;' ...
         'properties=batchconfig2propgrid(BATCH_CONFIG);' ...
         'properties = properties.GetHierarchy();' ...
         'bcp = PropertyGrid(gcf,' ...
         '''Properties'', properties,' ...
         '''Position'', [.36 .1 .6 .84]);']}, ...
...
        {'Style', 'pushbutton','string','Save as', ...
        'callback', ...
        ['global bcp;global BATCH_CONFIG;BATCH_CONFIG=propgrid2batchconfig(bcp,BATCH_CONFIG);', ...
        'for i=1:length(BATCH_CONFIG);', ...
        '    level_cell{i}=[''Level '',num2str(i),'' - '',BATCH_CONFIG(i).file_name];', ...
        'end;', ...
        'if length(level_cell)>1;', ...
        '    level_ind=pop_chansel(level_cell);', ...
        '    if isempty(level_ind);return;end;', ...
        'else;', ...
        '    level_ind=1;', ...
        'end;',...
        '[cfgfname,cfgfpath]=uiputfile(''*.cfg'',''Batch configuration file'');', ...
        'global bcp;global BATCH_CONFIG;BATCH_CONFIG=propgrid2batchconfig(bcp,BATCH_CONFIG);', ...
        'tmp_BATCH_CONFIG=BATCH_CONFIG;BATCH_CONFIG=tmp_BATCH_CONFIG(level_ind);', ...
        'if ~strcmp(BATCH_CONFIG.file_name,cfgfname);', ...
        '    disp(''updating the file_name property...'');', ...
        '    BATCH_CONFIG.file_name=cfgfname;',...
        'end;',...
        'save(fullfile(cfgfpath,cfgfname),''BATCH_CONFIG'');', ...
        'BATCH_CONFIG=tmp_BATCH_CONFIG;']}, ...
        {'Style', 'pushbutton','string','Clear/New', ...
        'callback', ...
        ['global BATCH_CONFIG;BATCH_CONFIG=batchconfig_obj;', ...
        'global bcp;' ...
        'properties=batchconfig2propgrid(BATCH_CONFIG);' ...
        'properties = properties.GetHierarchy();' ...
        'bcp = PropertyGrid(gcf,' ...
        '''Properties'', properties,' ...
        '''Position'', [.36 .1 .6 .84]);']}, ...
        }, ...
        'title', 'Batch configuration -- pop_batch_edit()',...%, ...
        'eval',['global BATCH_CONFIG;if ~isempty(BATCH_CONFIG);', ...
        'global bcp;' ...
        'properties=batchconfig2propgrid(BATCH_CONFIG);' ...
        'properties = properties.GetHierarchy();' ...
        'bcp = PropertyGrid(gcf,' ...
        '''Properties'', properties,' ...
        '''Position'', [.36 .1 .6 .84]);end;'] ...
        );

    if isempty(results);return;end

    global bcp;
    global BATCH_CONFIG;
    BATCH_CONFIG=propgrid2batchconfig(bcp,BATCH_CONFIG);
  
end;

%function s=propgristr(fnames)

%s=['global bcp;' ...
%   'properties=batchconfig2propgrid(BATCH_CONFIG,{',vararg2str(fnames),'});' ...
%   'properties = properties.GetHierarchy();' ...
%   'bcp = PropertyGrid(gcf,' ...
%   '''Properties'', properties,' ...
%   '''Position'', [.36 .1 .6 .84]);' ...
%   ]
