function properties = batchconfig2propgrid(batchconfig)

if nargin==0;%Use the global object BATCH_CONFIG
    global BATCH_CONFIG
    if isempty(BATCH_CONFIG);
        batchconfig=batchconfig_obj;
    else
        batchconfig=BATCH_CONFIG;
    end
end

for i=1:length(batchconfig);
    properties((i*17)-16:(i*17)) = [ ...
... % basic properties...
        PropertyGridField(['exec_func[',num2str(i),']'], batchconfig(i).exec_func, ...
        'Type', PropertyType('char', 'row', {'ef_gen_m','ef_current_base','ef_sqsub','ef_sqsub_sshfm','ef_mshpc'}), ...
        'Category', ['Level ',num2str(i),' - ',batchconfig(i).file_name], ...
        'DisplayName', ['exec_func[',num2str(i),']'], ...
        'Description', ['Name of the function that will execute the htb files.']) ...
        PropertyGridField(['replace_string[',num2str(i),']'], batchconfig(i).replace_string, ...
        'Type', PropertyType('cellstr', 'column'), ...
        'Category', ['Level ',num2str(i),' - ',batchconfig(i).file_name], ...
        'DisplayName', ['replace_string[',num2str(i),']'], ...
        'Description', ['The cell array of strings to swap into the History Template script files.']) ...
... % execute head...
        PropertyGridField(['qsub[',num2str(i),']'], [], ...
        'Category', ['Level ',num2str(i),' - ',batchconfig(i).file_name], ...
        'DisplayName', ['exec_config[',num2str(i),']']) ...
...% execute properties...
        PropertyGridField(['qsub[',num2str(i),'].job_name'], batchconfig(i).job_name, ...
        'Type', PropertyType('char', 'row'), ...
        'Category', ['Level ',num2str(i),' - ',batchconfig(i).file_name], ...
        'DisplayName', ['job_name'], ...
        'Description', ['Parameters for creating the job name (Batch string swap rules apply).']) ...
        PropertyGridField(['qsub[',num2str(i),'].session_init'], batchconfig(i).session_init, ...
        'Type', PropertyType('char', 'row'), ...
        'Category', ['Level ',num2str(i),' - ',batchconfig(i).file_name], ...
        'DisplayName', ['session_init'], ...
        'Description', ['Code [or file name of a text file containing code] to execute at the begining of a submission session.']) ...
        PropertyGridField(['qsub[',num2str(i),'].job_init'], batchconfig(i).job_init, ...
        'Type', PropertyType('char', 'row'), ...
        'Category', ['Level ',num2str(i),' - ',batchconfig(i).file_name], ...
        'DisplayName', ['job_init'], ...
        'Description', ['Code [or file name of a text file containing code] to execute at the begining of a job.']) ...
        PropertyGridField(['qsub[',num2str(i),'].m_init'], batchconfig(i).m_init, ...
        'Type', PropertyType('char', 'row'), ...
        'Category', ['Level ',num2str(i),' - ',batchconfig(i).file_name], ...
        'DisplayName', ['m_init'], ...
        'Description', ['Code [or file name of a text file containing code] to execute at the begining of the m file.']) ...
        PropertyGridField(['qsub[',num2str(i),'].queue'], batchconfig(i).queue, ...
        'Type', PropertyType('char', 'row'), ...
        'Category', ['Level ',num2str(i),' - ',batchconfig(i).file_name], ...
        'DisplayName', ['queue'], ...
        'Description', ['[sqsub -q input] The scheduller queue type to submit to. Options are: serial, threaded, mpi.']) ...
        PropertyGridField(['qsub[',num2str(i),'].run_time'], batchconfig(i).run_time, ...
        'Type', PropertyType('char', 'row'), ...
        'Category', ['Level ',num2str(i),' - ',batchconfig(i).file_name], ...
        'DisplayName', ['run_time'], ...
        'Description', ['[sqsub -r input] Run time limit for the this job (scheduler will terminate the process if it is in Run state for this duration)']) ...
        PropertyGridField(['qsub[',num2str(i),'].num_cores'], batchconfig(i).num_cores, ...
        'Type', PropertyType('denserealdouble', 'matrix'), ...
        'Category', ['Level ',num2str(i),' - ',batchconfig(i).file_name], ...
        'DisplayName', ['num_cores'], ...
        'Description', ['[sqsub -n input] The number of cores.']) ...
        PropertyGridField(['qsub[',num2str(i),'].num_nodes'], batchconfig(i).num_nodes, ...
        'Type', PropertyType('denserealdouble', 'matrix'), ...
        'Category', ['Level ',num2str(i),' - ',batchconfig(i).file_name], ...
        'DisplayName', ['num_nodes'], ...
        'Description', ['[sqsub -n input] The number of nodes.']) ...
        PropertyGridField(['qsub[',num2str(i),'].num_proc_per_node'], batchconfig(i).num_proc_per_node, ...
        'Type', PropertyType('denserealdouble', 'matrix'), ...
        'Category', ['Level ',num2str(i),' - ',batchconfig(i).file_name], ...
        'DisplayName', ['num_proc_per_node'], ...
        'Description', ['[sqsub -npp input] The number of procedures per node.']) ...
        PropertyGridField(['qsub[',num2str(i),'].num_thread_per_proc'], batchconfig(i).num_thread_per_proc, ...
        'Type', PropertyType('denserealdouble', 'matrix'), ...
        'Category', ['Level ',num2str(i),' - ',batchconfig(i).file_name], ...
        'DisplayName', ['num_thread_per_proc'], ...
        'Description', ['[sqsub -tpp input] The number of threads per procedure.']) ...
        PropertyGridField(['qsub[',num2str(i),'].memory_per_proc'], batchconfig(i).memory_per_proc, ...
        'Type', PropertyType('char', 'row'), ...
        'Category', ['Level ',num2str(i),' - ',batchconfig(i).file_name], ...
        'DisplayName', ['memory_per_proc'], ...
        'Description', ['[sqsub -mpp input] The amount of memory per process. (e.g. 100K, 6G, etc...)']) ...
        PropertyGridField(['qsub[',num2str(i),'].qsub_options'], batchconfig(i).qsub_options, ...
        'Type', PropertyType('cellstr', 'column'), ...
        'Category', ['Level ',num2str(i),' - ',batchconfig(i).file_name], ...
        'DisplayName', ['qsub_options'], ...
        'Description', ['Options ???.']) ...
        PropertyGridField(['qsub[',num2str(i),'].software'], batchconfig(i).software, ...
        'Type', PropertyType('char', 'row', {'matlab','octave','none'}), ...
        'Category', ['Level ',num2str(i),' - ',batchconfig(i).file_name], ...
        'DisplayName', ['software'], ...
        'Description', ['Name of the software to used in executing the code from History file number', num2str(i)]) ...
        PropertyGridField(['qsub[',num2str(i),'].program_options'], batchconfig(i).program_options, ...
        'Type', PropertyType('cellstr', 'column'), ...
        'Category', ['Level ',num2str(i),' - ',batchconfig(i).file_name], ...
        'DisplayName', ['program_options'], ...
        'Description', ['Options ???.']) ...
        ];
end
