function job_struct=ef_gen_m(job_struct)

%% BUILD THE DIRECTORY FOR THE TIME M FILES IN THE
% LOG PATH OF THE CURRENT ANALYSIS_ROOT FOLDER...
%make directory named by history fname and date-time stamp.
root_hfn=job_struct.batch_hfn(1:strfind(job_struct.batch_hfn,'.')-1);
dt=clock;
job_struct.m_path=sprintf('%s_%s-%s-%s_%s-%s', ...
    root_hfn, ...
    num2str(dt(1)), ...
    num2str(dt(2)), ...
    num2str(dt(3)), ...
    num2str(dt(4)), ...
    num2str(dt(5)));
mkdir(fullfile(job_struct.context_config.log,job_struct.m_path));

%% MATLAB OR OCTAVE EXECUTION (BUILD M FILE)...
if strcmp(job_struct.batch_config.software,'octave')||strcmp(job_struct.batch_config.software,'matlab');

   %% INITIATE BATCHINITSTR...
    batchInitStr='';
    
   %% M_INIT
   if exist(job_struct.batch_config.m_init,'file');
       fid_minit=fopen(job_struct.batch_config.m_init,'r');
       tmp_batchInitStr=fread(fid_minit,'char');
       batchInitStr=[batchInitStr,char(tmp_batchInitStr')];
   else
       batchInitStr=[batchInitStr,job_struct.batch_config.m_init];
   end
   
    %% GET THE STRING FROM THE HTB FILES AND START BUILDING BATCHHISTSTR...
    %Create batchHistStr from the current HistFName file...
    [cPath,root_hfn,cExt]=fileparts(job_struct.batch_hfn);
    eval(['fidRHT=fopen(''' job_struct.batch_hfp job_struct.batch_hfn ''',''r'');']);
    batchHistStr=char(fread(fidRHT,'char')');
    
    qsubstr='';
    
    disp(['Generating .m files in ',fullfile(job_struct.context_config.log,job_struct.m_path),'...']);
    %% START LOOP THROUGH DATA FILES...
    for bfni=1:length(job_struct.batch_dfn);
        % DO FOR EACH DATA FILE ...        
        %% INITIATE TMPHISTSTR...
        
        %% SWAP THE HISTORY STRING KEY STRINGS...        
        batchStr=batch_strswap([batchInitStr,batchHistStr],job_struct.batch_config, ...
            'datafname',job_struct.batch_dfn{bfni}, ...
            'datafpath',job_struct.batch_dfp, ...
            'log',job_struct.context_config.log, ...
            'local_project',job_struct.context_config.local_project, ...
            'local_dependency',job_struct.context_config.local_dependency, ...
            'remote_project_archive',job_struct.context_config.remote_project_archive, ...
            'remote_project_work',job_struct.context_config.remote_project_work, ...
            'remote_dependency',job_struct.context_config.remote_dependency, ...
            'mount_archive',job_struct.context_config.mount_archive, ...
            'mount_work',job_struct.context_config.mount_work);
                
        %% SAVE THE STRSWAPPED HISTORY STRING TO M FILE IN THE TIME STAMPED LOG PATH...
        % save cBatchFName m file...
        [cPath,root_dfn,cExt]=fileparts(job_struct.batch_dfn{bfni});
        c_mfn=[root_hfn,'_',root_dfn,'.m'];
        fidM=fopen(fullfile(job_struct.context_config.log,job_struct.m_path,c_mfn),'w');%WRITE M FILE TO LOG PATH...
        fwrite(fidM,batchStr,'char');
        fclose(fidM);
    end
end  

