function job_struct=ef_sshfm(job_struct)

%% LOAD THE QSUB.TXT FILE...

if ~isfield(job_struct,'user_password');
    if isfield(job_struct,'user_name');
        job_struct.user_password=logindlg('Title',[job_struct.user_name,'@',job_struct.host_name],'Password','only');
    else
        [job_struct.user_name,job_struct.user_password]=logindlg('Title',job_struct.host_name);
    end
end

%% INITIATE THE SSH CONNECTION...
conn=sshfrommatlab(job_struct.user_name, ...
    job_struct.host_name, ...
    job_struct.user_password);

%% SFTP FROMMATLAB M FILES TO THE REMOTE LOG...
zip([fullfile(job_struct.context_config.log,job_struct.m_path),'.zip'], ...
    '*.m',fullfile(job_struct.context_config.log,job_struct.m_path));
job_struct.remote_log=fullfile(job_struct.remote_work, ...
    job_struct.context_config.log, ...
    [job_struct.m_path,'.zip']);
job_struct.remote_log=strrep(job_struct.remote_log,'\','/');
sftpfrommatlab(job_struct.user_name, ...
    job_struct.host_name, ...
    job_struct.user_password, ...
    fullfile(cd,fullfile(job_struct.context_config.log, ...
    [job_struct.m_path,'.zip'])), ...
    job_struct.remote_log)

%% GET THE QSUBSTR
job_struct;
fid=fopen(fullfile(job_struct.context_config.log,job_struct.m_path,'qsub.txt'),'r');
qsubstr=fread(fid,'char');
qsubstr=char(qsubstr');

%% ISSUE THE SQSUBSTR...
[conn,result]=sshfrommatlabissue(conn,qsubstr);
%print results to the command line...
disp(result)

%% COLLECT THE NEW JOBIDS FROM THE SCHEDULLER...
job_struct.jobids={};
for bfi=1:length(job_struct.batch_dfn);
    jobidstr=strtrim(result{length(result)-length(job_struct.batch_dfn)+bfi});
    sinds=strfind(jobidstr,' ');
    job_struct.jobids{bfi}=jobidstr(sinds(end)+1:end);
end

%% CLOSE SSHFROMMATLAB CONNECTION...
sshfrommatlabclose(conn);
