
%% this should be isolated into submit functions...
%% Initiate the SSH connection... 
disp([subStrInit,qsubstr]);
conn=sshfrommatlab(job_struct.user_name, ...
    job_struct.host_name, ...
    job_struct.user_password);
%% issue subStrInit...
[conn,result]=sshfrommatlabissue(conn,[subStrInit,qsubstr]);
%print results to the command line...
disp(result)

%collect new jobids from the scheduller...
job_struct.jobids={};
for bfi=1:length(job_struct.batch_dfn);
    jobidstr=strtrim(result{length(result)-length(job_struct.batch_dfn)+bfi});
    sinds=strfind(jobidstr,' ');
    job_struct.jobids{bfi}=jobidstr(sinds(end)+1:end);
end

%close ssh from matlab...
sshfrommatlabclose(conn);
