function job_struct=rsub_sshfm(job_struct,order_inds)

%% LOAD THE QSUB.TXT FILE...

if ~isfield(job_struct(order_inds(1),order_inds(2)),'user_password');
    if isfield(job_struct(order_inds(1),order_inds(2)).context_config,'remote_user_name');
        job_struct(order_inds(1),order_inds(2)).user_password=logindlg('Title',[job_struct(order_inds(1),order_inds(2)).context_config.remote_user_name,'@',job_struct(order_inds(1),order_inds(2)).context_config.remote_exec_host],'Password','only');
    else
        [job_struct(order_inds(1),order_inds(2)).context_coonfig.remote_user_name,job_struct(order_inds(1),order_inds(2)).user_password]=logindlg('Title',job_struct(order_inds(1),order_inds(2)).context_config.remote_exec_host);
    end
end

%% INITIATE THE SSH CONNECTION...
conn=sshfrommatlab(job_struct(order_inds(1),order_inds(2)).context_config.remote_user_name, ...
    job_struct(order_inds(1),order_inds(2)).context_config.remote_exec_host, ...
    job_struct(order_inds(1),order_inds(2)).user_password);

%% SFTP FROMMATLAB M FILES TO THE REMOTE LOG...
zip([fullfile(job_struct(order_inds(1),order_inds(2)).context_config.log,job_struct(order_inds(1),order_inds(2)).m_path),'.zip'], ...
    '*.*',fullfile(job_struct(order_inds(1),order_inds(2)).context_config.log,job_struct(order_inds(1),order_inds(2)).m_path));
job_struct.remote_log=fullfile(job_struct(order_inds(1),order_inds(2)).remote_work, ...
    job_struct(order_inds(1),order_inds(2)).context_config.log, ...
    [job_struct(order_inds(1),order_inds(2)).m_path,'.zip']);
job_struct(order_inds(1),order_inds(2)).remote_log=strrep(job_struct(order_inds(1),order_inds(2)).remote_log,'\','/');
sftpfrommatlab(job_struct(order_inds(1),order_inds(2)).context_config.remote_user_name, ...
    job_struct(order_inds(1),order_inds(2)).context_config.remote_exec_host, ...
    job_struct(order_inds(1),order_inds(2)).user_password, ...
    fullfile(cd,fullfile(job_struct(order_inds(1),order_inds(2)).context_config.log, ...
    [job_struct(order_inds(1),order_inds(2)).m_path,'.zip'])), ...
    job_struct(order_inds(1),order_inds(2)).remote_log)

%% GET THE QSUBSTR... UPDATE TO EXECUTION OF BASH SCRIPT...
%job_struct;
unzipcom=['cd ',job_struct(order_inds(1),order_inds(2)).remote_work,'; ', ...
    'unzip ',[strrep(fullfile(job_struct(order_inds(1),order_inds(2)).context_config.log,job_struct(order_inds(1),order_inds(2)).m_path),'\','/'),'.zip -d '], ...
    strrep(fullfile(job_struct(order_inds(1),order_inds(2)).context_config.log,job_struct(order_inds(1),order_inds(2)).m_path),'\','/'),'; ' ...
    ' chmod 755 ',strrep(fullfile(job_struct(order_inds(1),order_inds(2)).context_config.log,job_struct(order_inds(1),order_inds(2)).m_path),'\','/'),'/submit.sh; ', ...
    strrep(fullfile(job_struct(order_inds(1),order_inds(2)).context_config.log,job_struct(order_inds(1),order_inds(2)).m_path),'\','/'),'/submit.sh;'];
[conn,result]=sshfrommatlabissue(conn,unzipcom);

%fid=fopen(fullfile(job_struct(order_inds(1),order_inds(2)).context_config.log,job_struct(order_inds(1),order_inds(2)).m_path,'submit.sh'),'r');
%qsubstr=fread(fid,'char');
%qsubstr=char(qsubstr');

%% ISSUE THE SQSUBSTR...
%[conn,result]=sshfrommatlabissue(conn,qsubstr);
%print results to the command line...
disp(result)

%% COLLECT THE NEW JOBIDS FROM THE SCHEDULLER...
job_struct.jobids={};
for bfi=1:length(job_struct.batch_dfn);
    jobidstr=strtrim(result{length(result)-length(job_struct(order_inds(1),order_inds(2)).batch_dfn)+bfi});
    sinds=strfind(jobidstr,' ');
    job_struct(order_inds(1),order_inds(2)).jobids{bfi}=jobidstr(sinds(end)+1:end);
end

%% CLOSE SSHFROMMATLAB CONNECTION...
sshfrommatlabclose(conn);
